version: '3.5'

services:
  backupper:
    build:
      context: services/backupper
    volumes: 
      - ./backup:/backup
    environment: 
      - SECRET=foo
      - FILE_PATH=/backup
    ports: 
      - 3000:3000  
  backer:
    build:
      context: services/backer
    restart: unless-stopped
    environment:
      - TOKEN_SECRET=very_big_sicrit
      - BACKUPPER_URL=jotainroskaa
      - PGUSER=postgres
      - CRON_SCHEDULE=* * * * * # cron schedule
      - SERVICE_NAME=lol # service name here
      - PGDB=lol2 # name of the database to dump 
      - PGHOST=db # hostname
      