name: Build & Publish Docker image

on:
  push:
    branches:
      - master
    paths:
      - 'services/backer/**'

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master/services/backer
      - name: Publish to DockerHub
        uses: docker/build-push-action@v1.1.0
        with:
          repository: toska/backer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: latest